### ISSUE TITLE
Candids Text is missing on Auth Pages

### ISSUE THREAD

**Issue by DivyanshBatham** [DivyanshBatham/cb-candids-client#28]
![image](https://user-images.githubusercontent.com/12484697/64955737-ab341a00-d8a6-11e9-9133-2149f3e924bc.png)

**Comment by errorr404** [comment]
Fixed!
fb70bf5

[https://stackoverflow.com/questions/45603664/svg-not-rendering-correctly-when-used-with-by-multiple-react-components](https://stackoverflow.com/questions/45603664/svg-not-rendering-correctly-when-used-with-by-multiple-react-components)
