### ISSUE TITLE
Comments color is not randomized 

### ISSUE THREAD

**Issue by DivyanshBatham** [DivyanshBatham/cb-candids-client#33]
![image](https://user-images.githubusercontent.com/12484697/65274846-e43beb00-db41-11e9-9e69-7163647a3f69.png)

**Comment by errorr404** [comment]
284fe84

![image](https://user-images.githubusercontent.com/29652551/65770093-ef4ed680-e152-11e9-882a-8045c75bff5e.png)
fixed!
