### ISSUE TITLE
Show outlined SVGs for Like and Comment

### ISSUE THREAD

**Issue by DivyanshBatham** [DivyanshBatham/cb-candids-client#34]
![image](https://user-images.githubusercontent.com/12484697/65274909-0f263f00-db42-11e9-8b28-4b0aba63a0d7.png)

1) Always show outlined for the unliked icon.
2) Show outlined for the comment icon.
3) Show solid for the comment icon (on hover).
4) Show solid for the liked icon.

**Comment by errorr404** [comment]
32a54bb  fixed!
![image](https://user-images.githubusercontent.com/29652551/65763984-2cf73380-e142-11e9-82e6-04ac7054d778.png)
